### ISSUE TITLE
pip install atari-py==0.2.0 failed

### ISSUE THREAD

**Issue by Vinxxiii** [openai/atari-py#55] opened 2019-06-27 22:55 UTC
On https://pypi.org/project/atari-py/ version 0.2.0 seems available.
But, on ubuntu 18.04 when executing the command : pip install atari-py==0.2.0
The following error occurs : 

 ERROR: Could not find a version that satisfies the requirement atari-py==0.2.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.14)

Also, the installation of atary-py version 0.1.15 seems not available too

**Comment by christopherhesse** [comment] 2019-06-29 00:00
Looks like a duplicate of https://github.com/openai/gym/issues/1568 thanks for reporting!

**Closed by christopherhesse** 2019-06-29 00:00 UTC
